"""date column in session 

Revision ID: b6ff6672af00
Revises: 0316ada6c2e3
Create Date: 2025-11-02 21:05:07.651357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ff6672af00'
down_revision: Union[str, Sequence[str], None] = '0316ada6c2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studysession', sa.Column('date', sa.Date(), nullable=False))
    # op.alter_column('users', 'password_hash',
    #            existing_type=sa.VARCHAR(),
    #            type_=sa.LargeBinary(),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('studysession', 'date')
    # ### end Alembic commands ###
